-- BUFFER KEYMAPS
-- currently testing out harpoon
-- vim.keymap.set("n", "<leader>bn", "<cmd>bnext<cr>")
-- vim.keymap.set("n", "<leader>bp", "<cmd>bprev<cr>")
-- vim.keymap.set("n", "<leader>bq", "<cmd>bd<cr>")
